"""Generate `tests/fixtures/m0/market_data.yaml` from `navall_sample.txt`.

The agreement test in `tests/unit/test_m0_provider.py` compares
`WarehouseMarketDataProvider` against `FakeMarketDataProvider`. That only
compares implementations if both hold identical data — otherwise it compares
fixtures, and passes for the wrong reason. So the fake's YAML is generated from
the same AMFI slice the warehouse is loaded from, by the same parser.

    python -m scripts.build_m0_fixture
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from src.m0_data.load import scheme_id_collisions
from src.m0_data.parse.nav.amfi import parse_navall

FIXTURES = Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "m0"
SAMPLE = FIXTURES / "navall_sample.txt"
TARGET = FIXTURES / "market_data.yaml"


def main() -> None:
    parsed = parse_navall(SAMPLE.read_text(encoding="utf-8").splitlines())
    # A colliding scheme_id would give the fake whichever row came last, which
    # is exactly the silent drop the warehouse warns about. Excluded from the
    # fixture so the two providers stay comparable.
    colliding = set(scheme_id_collisions(parsed.schemes))
    schemes = [s for s in parsed.schemes if s.scheme_id not in colliding]
    navs = [n for n in parsed.navs if n.scheme_id not in colliding]

    lines = [
        "# GENERATED by scripts/build_m0_fixture.py from navall_sample.txt.",
        "# Regenerate, do not hand-edit — the point of this file is that the fake",
        "# and the warehouse hold IDENTICAL data, so the agreement test compares",
        "# implementations rather than fixtures.",
        f"# Colliding scheme_ids excluded: {sorted(colliding) or 'none'}",
        "",
        "schemes:",
    ]
    for s in schemes:
        category = f'"{s.sebi_category}"' if s.sebi_category else "null"
        lines += [
            f"  - scheme_id: {s.scheme_id}",
            f'    scheme_name: "{s.scheme_name}"',
            f'    amfi_code: "{s.amfi_code}"',
            f"    isin: {s.isin or 'null'}",
            f"    plan: {s.plan}",
            f"    option: {s.option}",
            f"    sebi_category: {category}",
            "    status: active",
        ]

    by_scheme: dict[str, list] = defaultdict(list)
    for n in navs:
        by_scheme[n.scheme_id].append(n)
    lines += ["", "navs:"]
    for scheme_id, rows in by_scheme.items():
        lines.append(f"  {scheme_id}:")
        for n in sorted(rows, key=lambda x: x.nav_date):
            lines.append(
                f'    - {{nav_date: {n.nav_date}, nav: "{n.nav}", '
                "is_interpolated: false}"
            )

    index: dict[tuple[str, str], list] = defaultdict(list)
    for s in schemes:
        index[(s.scheme_name, s.option)].append(s)
    lines += ["", "sibling_plans:"]
    for s in schemes:
        peers = index[(s.scheme_name, s.option)]
        others = [o for o in peers if o.scheme_id != s.scheme_id]
        mapping = {}
        for plan in ("direct", "regular"):
            candidates = [o for o in others if o.plan == plan]
            if len(candidates) == 1:
                mapping[plan] = candidates[0].scheme_id
        if mapping:
            lines.append(f"  {s.scheme_id}:")
            lines += [f"    {k}: {v}" for k, v in mapping.items()]

    lines += ["", "mergers: []", "idcw_events: {}", "tax_class: {}", "ter: {}",
              "exit_load_days: {}", "benchmarks: []", "scheme_benchmarks: {}",
              "index_levels: {}", "risk_free: []", "aum: {}", ""]
    TARGET.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.name}: {len(schemes)} schemes, {len(navs)} navs, "
          f"{len(colliding)} colliding scheme_ids excluded")


if __name__ == "__main__":
    main()
