"""Render the V0.1 golden transactions as a CAS statement.

`BUILD_ORDER.md` R2 step V0.2 says the CAS parser *replaces* the hand-made CSV.
That is not true while the only statement the parser has ever seen is a
hand-written trap fixture: the golden portfolio — three real funds, real AMFI
NAVs, six SIP lots, a straddled LTCG boundary, two exit-load rates, a bounced
instalment and a switch — has to arrive through the parser too.

**What this proves, and what it does not.** The rows here are the same rows
`build_v0_fixture.py` computed; rendering and re-reading them does not
re-verify the arithmetic. The independent check on the arithmetic is
`verify_v0_ledger.py`, which recomputes longhand and imports nothing from
`src.m1_ledger`. What this adds is that the **parser** is a faithful inverse of
a realistic statement rendering — that folio, scheme, date, type, units, NAV
and running balance all survive the round trip on real data, at three NAV
scales, with charges on separate lines.

**Money prints at 2dp, because that is what a statement can express.** The
golden fixture holds charges at `MONEY_Q` (4dp) because it computes them from a
rate. No CAS carries that precision, so the round trip loses up to half a paisa
on every charge — a real property of the pipeline, asserted explicitly in
`tests/unit/test_v0_cas_gate.py` rather than rounded away here.

Usage:
    python -m scripts.build_v0_cas
"""

from __future__ import annotations

from collections import defaultdict
from decimal import Decimal
from pathlib import Path

from src.m1_ledger.txn import Txn, load_transactions

FIXTURES = Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "v0_ledger"
SOURCE = FIXTURES / "transactions.csv"
TARGET = FIXTURES / "cas_statement.txt"

#: The real ISINs, which since the re-key ARE the scheme_ids — MODULE_0.md §4.4
#: keys a scheme on its ISIN where one exists. Confirmed against AMFI's own NAV
#: history: 3,638 overlapping values, zero mismatches (DECISIONS V0-25).
#:
#: This map was invented placeholders (`INF000H01FC7`) until V0.5 produced the
#: real ones. Kept as an explicit identity map rather than deleted, because the
#: renderer needs *an* ISIN column and reading `scheme_id` directly would hide
#: the assumption that the two are the same thing.
ISINS = {
    "INF179K01UT0": "INF179K01UT0",
    "INF109K01761": "INF109K01761",
    "INF174KA1EZ1": "INF174KA1EZ1",
}
AMCS = {
    "INF179K01UT0": "HDFC Mutual Fund",
    "INF109K01761": "ICICI Prudential Mutual Fund",
    "INF174KA1EZ1": "Kotak Mahindra Mutual Fund",
}
#: How the registrar words each type. The parser maps these back through
#: `config/txn_types.yaml`, so wording that no pattern matches will fail the
#: import rather than being guessed at — which is the point.
DESCRIPTIONS = {
    "SIP": "Systematic Investment Purchase",
    "PURCHASE": "Purchase",
    "REDEMPTION": "Redemption",
    "SWITCH_OUT": "Switch Out",
    "SWITCH_IN": "Switch In",
    "REVERSAL": "Rejected - SIP Purchase",
}
CHARGE_LABELS = {
    "stamp_duty": "*** Stamp Duty ***",
    "stt": "*** STT ***",
    "exit_load": "*** Exit Load ***",
}


def indian(value: Decimal, places: int = 2) -> str:
    """Indian digit grouping: 2-2-3, not 3-3-3. `12,34,567.89`.

    MODULE_1.md §5.4 lists this as a trap for the reader; here it is a trap for
    the writer. Rendering with `{:,}` would produce Western grouping and quietly
    stop exercising the parser's comma handling on anything above a lakh.
    """
    text = f"{abs(value):,.{places}f}".replace(",", "")
    whole, _, frac = text.partition(".")
    if len(whole) > 3:
        head, tail = whole[:-3], whole[-3:]
        parts: list[str] = []
        while len(head) > 2:
            parts.insert(0, head[-2:])
            head = head[:-2]
        if head:
            parts.insert(0, head)
        whole = ",".join(parts) + "," + tail
    return f"{whole}.{frac}" if frac else whole


def printed_amount(t: Txn) -> Decimal:
    """What the amount column shows, in the registrar's own terms.

    A statement reports the money that moved, not the ledger's netted figure:
    a purchase shows the payment before stamp duty is taken out of it, and a
    redemption shows the proceeds before the load and STT come off. The
    importer reconstructs the ledger's convention from these plus the charge
    lines, which is the whole round trip under test.
    """
    amount = abs(t.amount or Decimal(0))
    if t.txn_type in {"SIP", "PURCHASE", "SWITCH_IN"}:
        return amount + t.stamp_duty
    return amount


def render(txns: list[Txn]) -> list[str]:
    """One folio block per scheme, transactions in printed order."""
    by_scheme: dict[tuple[str, str], list[Txn]] = defaultdict(list)
    for t in txns:
        by_scheme[(t.folio, str(t.scheme_id))].append(t)

    out = [
        " " * 26 + "CONSOLIDATED ACCOUNT STATEMENT",
        " " * 30 + "01-Jan-2024 To 30-Apr-2026",
        "",
        ">>> SYNTHETIC. Generated by scripts/build_v0_cas.py from",
        ">>> tests/fixtures/v0_ledger/transactions.csv. Regenerate, do not edit.",
        ">>> No real PAN, folio or holding appears here. Money prints at 2dp",
        ">>> because that is all a statement can express; the golden fixture",
        ">>> holds charges at 4dp, so the round trip loses up to half a paisa on",
        ">>> each. See DECISIONS V0-16.",
        "",
        "PAN: XXXXX0000X                              Email: investor@example.invalid",
        "",
    ]

    for (folio, scheme_id), rows in sorted(by_scheme.items()):
        rows.sort(key=lambda t: (t.txn_date, t.txn_seq, t.txn_ref))
        isin = ISINS[scheme_id]
        out += [
            f"Folio No: {folio}",
            AMCS[scheme_id],
            f"{rows[0].scheme_raw_name} - ISIN: {isin}",
            f"{'':8}Opening Unit Balance: 0.000000",
        ]
        for t in rows:
            out.append(txn_line(t))
            for field, label in CHARGE_LABELS.items():
                value: Decimal = getattr(t, field)
                if value:
                    out.append(f"{'':14}{label} {indian(value)}")
        closing = rows[-1].units_balance_rep or Decimal(0)
        out += [f"{'':8}Closing Unit Balance: {indian(closing, 6)}", ""]

    # The summary section, which must be skipped entirely (§5.4). Repeating a
    # real holding here is the point: if the state machine ever stopped
    # skipping it, every position in the golden portfolio would double.
    #
    # A real CAS repeats the holding AND its last transaction here, verbatim.
    # Rendering only a one-line holding summary would leave nothing for the
    # state machine to wrongly parse, and the skip would be untested — which is
    # exactly what mutation testing found.
    out += ["Portfolio Summary"]
    total = Decimal(0)
    for (_folio, scheme_id), rows in sorted(by_scheme.items()):
        closing = rows[-1].units_balance_rep or Decimal(0)
        # No `Folio No:` line here. §5.3 leaves IN_SUMMARY on the next folio
        # header, and a real CAS summary is a holdings table rather than a
        # repeat of the folio blocks — writing one in would be inventing a
        # layout to make a point, and would exit the skip legitimately.
        out += [
            f"{rows[0].scheme_raw_name} - ISIN: {ISINS[scheme_id]}",
            txn_line(rows[-1]),
            f"{'':8}Closing Unit Balance: {indian(closing, 6)}",
        ]
        total += closing * (rows[-1].nav or Decimal(0))
    out.append("Total Value" + " " * 24 + indian(total))
    return out


def txn_line(t: Txn) -> str:
    """One transaction row, in the registrar's column layout."""
    return (
        f"{t.txn_date:%d-%b-%Y}   {DESCRIPTIONS[t.txn_type]:<34}"
        f"{indian(printed_amount(t)):>14}"
        f"{_units(t):>16}"
        f"{indian(t.nav or Decimal(0), 4):>17}"
        f"{indian(t.units_balance_rep or Decimal(0), 6):>17}"
    )


def _units(t: Txn) -> str:
    """Units, with outflows in parentheses — the accounting convention (§5.4)."""
    units = t.units
    if units is None:
        return ""
    text = indian(units, 6)
    return f"({text})" if units < 0 else text


def main() -> None:
    txns = load_transactions(SOURCE)
    TARGET.write_text("\n".join(render(txns)) + "\n", encoding="utf-8")
    print(f"wrote {TARGET.relative_to(TARGET.parents[3])}  ({len(txns)} transactions)")


if __name__ == "__main__":
    main()
