"""Convert an AMFI historical-NAV workbook into a Decimal-safe YAML fixture.

Not part of `src/` — this is a one-off ingestion aid for V0.1 fixtures. M0's
real fetch and parse layer replaces it (`MODULE_0.md` §5-6), and when it does
this script should be deleted rather than promoted.

Two things it refuses to do quietly:

  - **Guess the plan.** The workbook's `Plan` column is authoritative and is
    written into the output. A Direct-plan series loaded against a Regular-plan
    scheme record is the ~1%/year silent error, and it is only caught by a value
    reconciliation, never by a unit one.

  - **Let a float through.** openpyxl parses the sheet's numeric literals into
    Python floats before we ever see them. Every value is routed through `str()`
    and quantised to `NAV_Q`, which is wider than the 4 decimal places the data
    actually carries, so nothing is lost and the scale is uniform. (Two NAVs in
    the supplied files are whole numbers stored without a decimal point, so the
    literal itself is not a reliable key — 1722 arrives as '1722.0'.)

Usage:
    python -m scripts.import_nav_xlsx <in.xlsx> [<in.xlsx> ...] -o <out.yaml>
"""

from __future__ import annotations

import argparse
from collections.abc import Iterator
from datetime import date, datetime
from decimal import Decimal
from itertools import pairwise
from pathlib import Path

import openpyxl
from src.common.decimals import NAV_Q

# Row layout of the AMFI export: four title rows, then a header row, then data.
HEADER_ROW = 5
FIRST_DATA_ROW = 6
FUND_NAME_ROW = 4
AMC_NAME_ROW = 2
EXPECTED_HEADER = (
    "Net Asset Value",
    "Repurchase Price",
    "Sale Price",
    "Date",
    "Plan",
    "Option",
)


class NavSheetError(RuntimeError):
    """The workbook is not shaped the way this importer expects.

    Raised rather than best-effort parsed: a silently misread column would put
    a repurchase price into a NAV series.
    """


def _cell(ws: object, row: int) -> str:
    value = ws.cell(row, 1).value  # type: ignore[attr-defined]
    return str(value).strip() if value is not None else ""


def read_workbook(path: Path) -> tuple[dict[str, str], list[tuple[date, Decimal]]]:
    """Return (metadata, [(nav_date, nav)]) from one AMFI export."""
    ws = openpyxl.load_workbook(path, data_only=True).active
    if ws is None:
        raise NavSheetError(f"{path.name}: no active worksheet")

    header = tuple(str(ws.cell(HEADER_ROW, c).value or "").strip() for c in range(1, 7))
    if header != EXPECTED_HEADER:
        raise NavSheetError(
            f"{path.name}: unexpected header {header!r}; expected {EXPECTED_HEADER!r}"
        )

    plans: set[str] = set()
    options: set[str] = set()
    series: list[tuple[date, Decimal]] = []

    for row in ws.iter_rows(min_row=FIRST_DATA_ROW, values_only=True):
        nav_raw, _repurchase, _sale, on, plan, option = row
        if nav_raw is None or on is None:
            continue
        # str() first: openpyxl hands back a float, and Decimal(float) would
        # capture the binary error rather than the printed value.
        nav = Decimal(str(nav_raw)).quantize(NAV_Q)
        when = on.date() if isinstance(on, datetime) else on
        series.append((when, nav))
        plans.add(str(plan).strip())
        options.add(str(option).strip())

    if not series:
        raise NavSheetError(f"{path.name}: no data rows")
    if len(plans) != 1 or len(options) != 1:
        raise NavSheetError(
            f"{path.name}: mixed plan/option in one sheet — plans={plans}, "
            f"options={options}. These are different schemes with different NAV "
            f"series and must not share a series."
        )

    series.sort()
    meta = {
        "amc": _cell(ws, AMC_NAME_ROW),
        "fund": _cell(ws, FUND_NAME_ROW),
        "plan": plans.pop(),
        "option": options.pop(),
        "source_file": path.name,
    }
    return meta, series


def gaps(
    series: list[tuple[date, Decimal]], threshold: int = 4
) -> list[tuple[date, date, int]]:
    """Calendar gaps wider than `threshold` days.

    `MODULE_0.md` §11.4 guarantees no gaps over 3 business days for held
    schemes, because XIRR needs a NAV on cashflow dates. A four-day gap is an
    ordinary weekend; anything longer is a market holiday or missing data, and
    the caller should know which.
    """
    return [
        (a[0], b[0], (b[0] - a[0]).days)
        for a, b in pairwise(series)
        if (b[0] - a[0]).days > threshold
    ]


def to_yaml(
    entries: list[tuple[str, dict[str, str], list[tuple[date, Decimal]]]],
) -> Iterator[str]:
    yield "# NAV series — generated by scripts/import_nav_xlsx.py. Do not hand-edit."
    yield "#"
    yield "# Every value is a quoted decimal string: the source is an xlsx, whose"
    yield "# numerics openpyxl parses as floats, so the conversion goes through str()"
    yield "# and is quantised to 6dp. The data carries 4."
    yield "#"
    yield "# `plan` is copied from the workbook, not assumed. A Direct series under a"
    yield "# Regular scheme record differs by ~1%/year and only a VALUE reconciliation"
    yield "# catches it — PLAN.md §7 V0."
    yield ""
    yield "series:"
    for scheme_id, meta, rows in entries:
        yield f"  {scheme_id}:"
        yield f"    fund: {meta['fund']!r}"
        yield f"    amc: {meta['amc']!r}"
        yield f"    plan: {meta['plan']!r}"
        yield f"    option: {meta['option']!r}"
        yield f"    source_file: {meta['source_file']!r}"
        yield f"    first_date: {rows[0][0].isoformat()}"
        yield f"    last_date: {rows[-1][0].isoformat()}"
        yield f"    row_count: {len(rows)}"
        yield "    navs:"
        for when, nav in rows:
            yield f'      {when.isoformat()}: "{nav}"'
        yield ""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("inputs", nargs="+", type=Path)
    ap.add_argument("-o", "--out", type=Path, required=True)
    ap.add_argument(
        "--scheme-id",
        action="append",
        required=True,
        help="scheme_id for each input, in the same order",
    )
    args = ap.parse_args()

    if len(args.scheme_id) != len(args.inputs):
        raise SystemExit("one --scheme-id per input file")

    entries = []
    for scheme_id, path in zip(args.scheme_id, args.inputs, strict=True):
        meta, series = read_workbook(path)
        found = gaps(series)
        print(f"{path.name}")
        print(f"  fund   : {meta['fund']}")
        print(f"  plan   : {meta['plan']} / {meta['option']}")
        print(f"  rows   : {len(series)}  {series[0][0]} .. {series[-1][0]}")
        print(f"  gaps>4d: {len(found)} {found[:3]}")
        entries.append((scheme_id, meta, series))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(to_yaml(entries)), encoding="utf-8")
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
