"""V0.3 — the acceptance gate, run against a ledger that came through the parser.

`BUILD_ORDER.md` R2: V0.2 is "CAS parser -> replaces the hand-made CSV", V0.3 is
"reconciliation against your own CAS", and V0.3 is the **V0 GATE**. Until the
golden portfolio arrives through `parse_cas` rather than `csv.DictReader`, the
replacement has not happened and the gate is being run on the wrong input.

`tests/fixtures/v0_ledger/cas_statement.txt` is that portfolio rendered as a
statement — three real funds on real AMFI NAVs, six SIP lots, a redemption
straddling the LTCG boundary, two exit-load rates, a bounced instalment and a
switch. It is generated by `scripts/build_v0_cas.py`.

What this establishes and what it does not: the rows were computed by
`build_v0_fixture.py`, so re-reading them does not re-verify the arithmetic —
`scripts/verify_v0_ledger.py` remains the independent check on that, recomputing
longhand and importing nothing from `src.m1_ledger`. What is established here is
that the parser is a faithful inverse of a realistic statement, and that the
acceptance gate still passes on the far side of it.
"""

from __future__ import annotations

import re
from datetime import date
from decimal import Decimal
from pathlib import Path

import pytest
from scripts.build_v0_cas import ISINS
from src.common.fixtures import FixtureStore, load_yaml
from src.common.types import Isin, SchemeId, UserId
from src.m0_data.providers.fake import FakeMarketDataProvider
from src.m1_ledger.cas import ImportReport, StagedTxn, import_cas
from src.m1_ledger.lots import build_book
from src.m1_ledger.reconcile import apply_gate, nav_cross_check, reconcile_all
from src.m1_ledger.returns import build_cashflows, npv, xirr
from src.m1_ledger.txn import Txn, drop_reversed, load_transactions

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "v0_ledger"
STATEMENT = FIXTURES / "cas_statement.txt"
USER = UserId("USER-01")
AS_OF = date(2026, 9, 4)
DATE_LINE = re.compile(r"^\d{2}-[A-Za-z]{3}-\d{4}\s")

#: Since the re-key these ARE the ISINs, confirmed against AMFI's own NAV
#: history (DECISIONS V0-25). MODULE_0.md §4.4 keys a scheme on its ISIN.
HDFC_DIRECT = SchemeId("INF179K01UT0")
ICICI_REGULAR = SchemeId("INF109K01761")
KOTAK_DIRECT = SchemeId("INF174KA1EZ1")

#: Money on a statement is printed to 2dp; the golden fixture computes charges
#: from a rate at `MONEY_Q` (4dp). Half a paisa is the most one rounding can
#: lose, so a field derived from a rate is bounded by it — and a field derived
#: from two rounded figures by twice it. Asserting the bound, and exactly which
#: fields carry it, is the point. See DECISIONS V0-16.
PRINTING_LOSS = Decimal("0.005")

#: Every money field the golden fixture computes from a rate, named. The round
#: trip cannot reproduce any of them, and nothing else may join the list
#: without this test failing — which is what stops "a paisa here and there"
#: from becoming the explanation for a real parser bug.
RATE_DERIVED: dict[tuple[str, str], Decimal] = {
    ("T009", "stt"): PRINTING_LOSS,
    ("T009", "exit_load"): PRINTING_LOSS,
    ("T010", "stt"): PRINTING_LOSS,
    ("T011", "stamp_duty"): PRINTING_LOSS,
    # The switch-IN amount is `proceeds - stamp_duty`, and BOTH are printed at
    # 2dp, so it inherits two roundings rather than one.
    ("T011", "amount"): PRINTING_LOSS * 2,
    ("T014", "stt"): PRINTING_LOSS,
    ("T014", "exit_load"): PRINTING_LOSS,
}

#: Fields that cannot survive the round trip, and why.
#: `txn_ref` is explicitly "not persisted" (MODULE_1.md §4.3) and is
#: regenerated from folio/scheme/date; `reverses_txn_ref` points at one.
#: `txn_seq` is re-derived per (folio, scheme, date) — see the test below.
NOT_ROUND_TRIPPED = {"txn_ref", "reverses_txn_ref", "txn_seq"}


#: M0's resolver, reached the way M1 reaches everything in M0 — through the
#: interface. This was a dict lookup in a lambda until the re-key gave the
#: golden schemes their real ISINs; a stub cannot exercise §11.3's ordering,
#: and it was the last place in the V0 gate where scheme identity did not
#: trace to a source file (`PLAN.md` §4.2).
_PROVIDER = FakeMarketDataProvider(FixtureStore(FIXTURES))


def _resolve(s: StagedTxn) -> SchemeId | None:
    """Resolve one staged CAS row through `MarketDataProvider`. §11.3."""
    ref = _PROVIDER.resolve_scheme(
        Isin(s.scheme_raw_isin) if s.scheme_raw_isin else None,
        s.scheme_raw_name,
        None,
        s.txn_date,
    )
    return ref.scheme_id


@pytest.fixture(scope="module")
def lines() -> list[str]:
    text = STATEMENT.read_text(encoding="utf-8")
    return [ln for ln in text.splitlines() if not ln.lstrip().startswith(">>>")]


@pytest.fixture(scope="module")
def report(lines: list[str]) -> ImportReport:
    return import_cas(USER, lines, _resolve)


@pytest.fixture(scope="module")
def golden() -> list[Txn]:
    return load_transactions(FIXTURES / "transactions.csv")


@pytest.fixture(scope="module")
def navs() -> dict[str, dict[date, Decimal]]:
    raw = load_yaml(FIXTURES / "nav_series.yaml")["series"]
    return {k: {d: Decimal(str(v)) for d, v in b["navs"].items()} for k, b in raw.items()}


def _key(t: Txn) -> tuple[str, str, date, str]:
    """Identity independent of parse position, so the two sides are comparable."""
    return (t.folio, str(t.scheme_id), t.txn_date, t.txn_type)


# --- the statement reads cleanly -------------------------------------------


def test_the_golden_statement_imports_without_a_single_problem(
    report: ImportReport,
) -> None:
    """No unmapped description, no unread line, nothing quarantined.

    This is stricter than it looks. `status == "ok"` requires that every one of
    the six registrar wordings maps through `config/txn_types.yaml`, and that
    not one line of a fourteen-transaction, three-folio statement — headers,
    balances, charge lines, summary — fell through to `unparsed`.
    """
    assert report.status == "ok"
    assert report.inserted == 14
    assert report.unmatched == 0
    assert report.unparsed_lines == 0
    assert report.quarantined == []
    assert report.ctx.unparsed == []


def test_every_scheme_resolves_on_its_isin(report: ImportReport) -> None:
    """§5.4: "Always resolve on ISIN, never name.\""""
    assert not any(f == "UNRESOLVED_SCHEME" for _, f in report.flags)
    assert {str(t.scheme_id) for t in report.txns} == set(ISINS)


# --- the round trip ---------------------------------------------------------


def test_the_statement_round_trips_to_the_golden_ledger(
    report: ImportReport, golden: list[Txn]
) -> None:
    """Field for field, on everything a statement can carry exactly.

    Dates, types, folios, units, NAVs, amounts and the printed running balance
    all survive rendering to a CAS and reading it back, across three NAV scales
    spanning two orders of magnitude. The exceptions are declared in
    `RATE_DERIVED` and checked by the next test; a field drifting out of one
    set and into the other fails both.
    """
    assert len(report.txns) == len(golden) == 14
    by_key = {_key(t): t for t in report.txns}
    assert set(by_key) == {_key(t) for t in golden}

    for want in golden:
        got = by_key[_key(want)]
        for f in Txn.__dataclass_fields__:
            if f in NOT_ROUND_TRIPPED | {"switch_group_id"}:
                continue
            if (want.txn_ref, f) in RATE_DERIVED:
                continue
            assert getattr(got, f) == getattr(want, f), f"{want.txn_ref}.{f}"


def test_a_statement_cannot_carry_the_charge_precision_the_fixture_holds(
    report: ImportReport, golden: list[Txn]
) -> None:
    """DECISIONS V0-16. The one thing the round trip genuinely loses.

    `build_v0_fixture.py` computes STT and exit load from a rate and keeps them
    at `MONEY_Q` — 0.3941, 273.2983. No statement prints that; a CAS shows 0.39
    and 273.30. So a charge read from a statement and a charge computed from a
    rate disagree by up to half a paisa, permanently and by construction.

    That is a real property of the pipeline rather than a rounding nuisance: the
    two sources must never be mixed within one position, and the statement —
    being what the AMC actually charged — is the one to believe.

    The set is closed. Every difference is named in `RATE_DERIVED`, each is
    inside its own bound, and no other field differs at all — so this cannot
    become a blanket tolerance that hides a real misread later.
    """
    by_key = {_key(t): t for t in report.txns}
    observed: set[tuple[str, str]] = set()

    for want in golden:
        got = by_key[_key(want)]
        for f in Txn.__dataclass_fields__:
            if f in NOT_ROUND_TRIPPED | {"switch_group_id"}:
                continue
            a, b = getattr(want, f), getattr(got, f)
            if a == b:
                continue
            observed.add((want.txn_ref, f))
            bound = RATE_DERIVED.get((want.txn_ref, f))
            assert bound is not None, f"undeclared difference {want.txn_ref}.{f}"
            assert abs(b - a) <= bound, f"{want.txn_ref}.{f} off by {abs(b - a)}"

    assert observed == set(RATE_DERIVED), "the declared set must be exact"


def test_txn_seq_is_re_derived_and_the_hand_assigned_value_is_not_needed(
    report: ImportReport, golden: list[Txn]
) -> None:
    """The golden CSV hand-assigns `txn_seq=1` to one row; the rule gives it 0.

    That row is the switch-IN leg, numbered 1 by hand to separate it from the
    switch-OUT booked the same day. The two sit in different folios and
    different schemes, so per (folio, scheme, date) they never collided and the
    discriminator was never doing anything.

    This is the V0-15 sequencing rule showing its shape: `txn_seq` orders rows
    that genuinely compete for FIFO position, and nothing else.
    """
    hand_assigned = [t for t in golden if t.txn_seq != 0]
    assert len(hand_assigned) == 1
    assert hand_assigned[0].txn_type == "SWITCH_IN"

    assert all(t.txn_seq == 0 for t in report.txns)
    scoped = [(t.folio, str(t.scheme_id), t.txn_date) for t in report.txns]
    assert len(scoped) == len(set(scoped)), "no two rows compete for the same slot"


def test_the_bounced_instalment_and_its_reversal_relink_after_the_round_trip(
    report: ImportReport, golden: list[Txn]
) -> None:
    """`reverses_txn_ref` is rebuilt from the data, not carried by the statement.

    A CAS does not print the link — §5.9 exists because it has to be inferred.
    So the round trip is only faithful if the inference lands on the same pair,
    and the consequence is what `drop_reversed` removes.
    """
    reversal = next(t for t in report.txns if t.txn_type == "REVERSAL")
    original = next(
        t for t in report.txns if t.txn_ref == reversal.reverses_txn_ref
    )
    assert original.txn_type == "SIP"
    assert original.txn_date == date(2024, 7, 1)
    assert original.units is not None and reversal.units is not None
    assert original.units + reversal.units == 0

    assert len(drop_reversed(report.txns)) == len(drop_reversed(golden)) == 12


# --- the fixture defect the round trip exposed ------------------------------


def test_the_golden_switch_crosses_amcs_and_therefore_cannot_be_linked(
    report: ImportReport, golden: list[Txn]
) -> None:
    """DECISIONS V0-16. A switch is intra-AMC by definition.

    The golden fixture switches HDFC -> ICICI. That is not a switch: units in
    one fund house cannot become units in another, so what it describes is a
    redemption followed by a purchase. The CSV carried `switch_group_id=SW001`
    because a human typed it, and nothing ever checked whether the pairing was
    possible.

    §5.8 joins the legs on `folio`, which is correct — a real switch keeps the
    folio — so the round trip cannot reproduce the hand-typed link and flags
    `UNLINKED_SWITCH` instead. The flag is right and the fixture is wrong.

    Nothing downstream breaks: §5.8 calls this a warning precisely because the
    lot engine treats each leg independently. Fixing it needs a second scheme
    from one AMC with a real NAV series, which is a data request.
    """
    out_leg = next(t for t in report.txns if t.txn_type == "SWITCH_OUT")
    in_leg = next(t for t in report.txns if t.txn_type == "SWITCH_IN")
    assert out_leg.folio != in_leg.folio
    # Since the re-key these are real ISINs, so the AMC is the issuer prefix
    # rather than something parsed out of a placeholder string.
    assert out_leg.scheme_id == HDFC_DIRECT      # INF179... = HDFC
    assert in_leg.scheme_id == ICICI_REGULAR     # INF109... = ICICI Prudential
    assert str(out_leg.scheme_id)[:6] != str(in_leg.scheme_id)[:6]

    assert [f for _, f in report.flags] == ["UNLINKED_SWITCH"]
    assert out_leg.switch_group_id is None

    # The CSV asserts the link a real statement could never support.
    golden_out = next(t for t in golden if t.txn_type == "SWITCH_OUT")
    golden_in = next(t for t in golden if t.txn_type == "SWITCH_IN")
    assert golden_out.switch_group_id == golden_in.switch_group_id == "SW001"
    assert golden_out.folio != golden_in.folio


# --- PLAN.md §7: the V0 acceptance gate, on the parsed ledger ---------------


def test_gate_every_folio_reconciles(
    report: ImportReport, navs: dict[str, dict[date, Decimal]]
) -> None:
    """`|computed - reported| <= 0.001`, on balances read off the statement.

    The reported balance is no longer a CSV column someone maintained by hand
    — it is the running balance the statement printed after each entry, parsed
    from the same line as the transaction. That is the independent figure §11.1
    needs, arriving the way it will in production.
    """
    book = build_book(report.txns)
    results = reconcile_all(book, report.txns, navs, AS_OF)

    assert len(results) == 3
    assert {r.status for r in results} == {"ok"}
    assert all(r.delta_units == Decimal(0) for r in results)
    assert apply_gate(results).passed
    assert apply_gate(results).excluded_scheme_ids == set()


def test_gate_the_nav_cross_check_passes_on_every_scheme(
    report: ImportReport, navs: dict[str, dict[date, Decimal]]
) -> None:
    """V0-12's witness, against NAVs that came off the statement.

    Every transaction's printed NAV is compared to our resolved scheme's NAV on
    the same date. This is the check that catches a Direct series filed against
    a Regular record — the real V0-05 error — and on this data it agrees
    everywhere, which is what says the three schemes resolved correctly.
    """
    for scheme_id in ISINS:
        scoped = [t for t in report.txns if str(t.scheme_id) == scheme_id]
        check = nav_cross_check(scoped, navs[scheme_id])
        assert check.status == "ok", scheme_id
        assert check.mismatched == 0
        assert check.checked == len(drop_reversed(scoped))
        assert check.worst_deviation_pct == Decimal(0), "printed NAV IS the series"


def test_gate_xirr_is_solvable_and_its_npv_returns_to_zero(
    report: ImportReport, navs: dict[str, dict[date, Decimal]]
) -> None:
    """`PLAN.md` §7: XIRR must match an independent calculation to 4dp.

    The independent calculation is a human step in a spreadsheet. What is
    machine-checkable is the defining property: discounting the cashflows at
    the solved rate returns a present value of zero. Asserted on cashflows
    built from the parsed ledger, so a parser that misread an amount or a sign
    would not produce a rate that closes.
    """
    book = build_book(report.txns)
    scheme_id = "INF174KA1EZ1"
    scoped = [t for t in report.txns if str(t.scheme_id) == scheme_id]

    units = sum(
        (
            lot.units_remaining
            for lot in book.all_lots()
            if lot.scheme_id == SchemeId(scheme_id)
        ),
        Decimal(0),
    )
    nav = max(d for d in navs[scheme_id] if d <= AS_OF)
    flows = build_cashflows(scoped, "scheme", units * navs[scheme_id][nav], AS_OF)
    rate = xirr(flows)

    assert rate is not None
    assert abs(npv(flows, rate)) < Decimal("0.01")
    assert Decimal("-0.5") < rate < Decimal("2.0"), "a plausible annualised rate"


def test_gate_reimporting_the_statement_produces_zero_new_rows(
    lines: list[str], report: ImportReport
) -> None:
    """`PLAN.md` §7's last gate condition, on the golden portfolio.

    V0-15 made this real; this runs it on fourteen transactions across three
    folios rather than on the trap fixture.
    """
    again = import_cas(
        USER, lines, _resolve, known_txn_ids={t.txn_id for t in report.txns}
    )
    assert again.inserted == 0
    assert again.duplicate == 14
    assert again.txns == []


def test_gate_the_ledger_is_byte_identical_on_a_second_parse(lines: list[str]) -> None:
    """`CLAUDE.md` invariant 10: a rebuild reproduces the same rows.

    Nothing in the pipeline may depend on iteration order, dict ordering or a
    generated identifier. `txn_ref` is generated, so this also pins that it is
    generated deterministically.
    """
    first = import_cas(USER, lines, _resolve)
    second = import_cas(USER, lines, _resolve)
    assert first.txns == second.txns
    assert [t.txn_id for t in first.txns] == [t.txn_id for t in second.txns]


def test_the_summary_repeats_a_real_transaction_and_it_is_still_skipped(
    lines: list[str], report: ImportReport
) -> None:
    """§5.4's first trap, on the golden portfolio rather than a toy.

    A CAS summary repeats each holding's closing position. This statement's
    summary carries the last transaction of every scheme verbatim — the HDFC
    switch-out, the ICICI switch-in and the Kotak redemption — so a state
    machine that stopped skipping it would book three extra transactions and
    every position would move.

    Mutation testing is why this is asserted. The summary originally rendered
    as one line per holding, which left nothing for the skip to be tested
    against: removing the skip changed nothing and the mutant survived.
    """
    summary_at = next(i for i, ln in enumerate(lines) if ln == "Portfolio Summary")
    repeated = [ln for ln in lines[summary_at:] if DATE_LINE.match(ln)]
    assert len(repeated) == 3, "the summary must contain transaction-shaped lines"
    assert any("Switch Out" in ln for ln in repeated)

    assert len(report.txns) == 14
    assert all(
        t.txn_ref
        for t in report.txns
    )
    # Every parsed row came from above the summary.
    reparsed = import_cas(USER, lines[:summary_at], _resolve)
    assert [t.txn_id for t in reparsed.txns] == [t.txn_id for t in report.txns]


def test_the_two_printed_balances_agree_with_each_other_and_with_the_ledger(
    report: ImportReport,
) -> None:
    """A statement prints the position twice, and both must tie.

    Each transaction line carries the running balance after it; each scheme
    block ends with an explicit `Closing Unit Balance`. They are independent
    figures on the page, and the ledger replayed from the transactions is a
    third. Reconciliation only ever consulted the running balance, so the
    closing line was going unchecked — a mutant that deleted it entirely
    survived a green suite.
    """
    book = build_book(report.txns)
    for scheme_id, isin in ISINS.items():
        scoped = [t for t in report.txns if str(t.scheme_id) == scheme_id]
        folio = scoped[0].folio

        printed_closing = report.ctx.closing_balance(folio, isin)
        last_running = max(
            scoped, key=lambda t: (t.txn_date, t.txn_seq, t.txn_ref)
        ).units_balance_rep
        computed = sum(
            (
                lot.units_remaining
                for lot in book.all_lots()
                if lot.folio == folio and lot.scheme_id == SchemeId(scheme_id)
            ),
            Decimal(0),
        )
        assert printed_closing is not None
        assert printed_closing == last_running, f"{scheme_id}: page disagrees with itself"
        assert printed_closing == computed, f"{scheme_id}: ledger disagrees with the page"


def test_the_importer_reads_a_gross_or_a_net_amount_column_the_same_way(
    report: ImportReport,
) -> None:
    """Registrars differ on whether the amount column includes stamp duty.

    Nothing in the corpus says which convention a given registrar uses, so the
    importer settles it per row against `units x nav` rather than picking one.
    This renders the same statement both ways and asserts the readings agree.

    They agree, but not to the last paisa, and the reason is worth stating.
    The amount that bought the units is Rs 22,710.4873. Printed gross it
    appears as 22,711.62 and the duty is subtracted to give 22,710.48; printed
    net it appears directly as 22,710.49. Both are the same figure rounded at
    a different point, one paisa apart — the V0-16 printing loss again, not a
    misread. What must hold exactly is that every non-money field is identical
    and that the amount is always the money that bought the units.

    Found by mutation testing: rendering the netted amount instead of the
    payment changed nothing, which was correct behaviour but accidental rather
    than asserted.
    """
    gross_lines = _render(printed_gross=True)
    net_lines = _render(printed_gross=False)
    assert gross_lines != net_lines, "the two renderings must actually differ"

    a = import_cas(USER, gross_lines, _resolve)
    b = import_cas(USER, net_lines, _resolve)
    assert a.status == b.status == "ok"
    assert a.txns == report.txns, "gross is what the golden statement renders"

    for x, y in zip(a.txns, b.txns, strict=True):
        for f in Txn.__dataclass_fields__:
            if f == "amount":
                continue
            assert getattr(x, f) == getattr(y, f), f"{x.txn_ref}.{f}"

        assert x.amount is not None and y.amount is not None
        assert abs(abs(x.amount) - abs(y.amount)) <= PRINTING_LOSS * 2

        # The convention was identified in both renderings: the stored amount
        # is the consideration that actually bought or sold the units.
        if x.units and x.nav and x.txn_type != "REVERSAL":
            product = (abs(x.units) * x.nav).quantize(Decimal("0.0001"))
            for amount in (x.amount, y.amount):
                assert abs(abs(amount) - product) <= PRINTING_LOSS * 2, x.txn_ref


def _render(*, printed_gross: bool) -> list[str]:
    """Re-render the golden statement with the other amount convention."""
    import scripts.build_v0_cas as gen

    original = gen.printed_amount
    if not printed_gross:
        gen.printed_amount = lambda t: abs(t.amount or Decimal(0))
    try:
        return [
            ln
            for ln in gen.render(load_transactions(FIXTURES / "transactions.csv"))
            if not ln.lstrip().startswith(">>>")
        ]
    finally:
        gen.printed_amount = original


# --- PLAN.md §8.3: the five property invariants, on the parsed book ---------


def test_gate_invariant_1_unit_conservation(report: ImportReport) -> None:
    """Sum of `lot.units_remaining` == sum of signed transaction units."""
    book = build_book(report.txns)
    assert book.total_units_remaining() == book.signed_txn_units(report.txns)


def test_gate_invariant_2_cost_conservation(report: ImportReport) -> None:
    """Cost is neither created nor destroyed — exact since V0-10."""
    book = build_book(report.txns)
    remaining = sum((lot.cost_remaining for lot in book.all_lots()), Decimal(0))
    allocated = sum(
        (
            c.cost_allocated
            for c in book.all_consumptions()
            if c.cost_basis_method == "actual"
        ),
        Decimal(0),
    )
    opened = sum((lot.cost_total for lot in book.all_lots()), Decimal(0))
    assert remaining + allocated == opened


def test_gate_invariant_3_fifo_ordering_is_monotonic(report: ImportReport) -> None:
    book = build_book(report.txns)
    for txn_ref in book.closing_txn_refs():
        seq = [c.acquisition_date for c in book.consumptions_for(txn_ref)]
        assert seq == sorted(seq)


def test_gate_invariant_4_pnl_closure(
    report: ImportReport, navs: dict[str, dict[date, Decimal]]
) -> None:
    """`realised + unrealised == market_value + proceeds - invested_gross`.

    The same profit reached two ways — by summing what each lot did, and by
    netting all the money that ever moved. They agree only if no cost or
    proceeds went missing anywhere in the FIFO chain.

    Asserted on charges READ FROM THE STATEMENT rather than computed from a
    rate. Both sides draw on the same figures, so the V0-16 printing loss
    cancels and the closure is exact — which is the point: a ledger built from
    a statement is internally consistent on the statement's own numbers.
    """
    book = build_book(report.txns)
    realised = sum((c.gain_amount for c in book.all_consumptions()), Decimal(0))
    proceeds = sum((c.proceeds_net for c in book.all_consumptions()), Decimal(0))
    invested_gross = sum((lot.cost_total for lot in book.all_lots()), Decimal(0))

    market_value = Decimal(0)
    cost_remaining = Decimal(0)
    for scheme_id in ISINS:
        units = book.units_remaining(SchemeId(scheme_id))
        if units == 0:
            continue
        nav = max(d for d in navs[scheme_id] if d <= AS_OF)
        market_value += units * navs[scheme_id][nav]
        cost_remaining += book.cost_basis_remaining(SchemeId(scheme_id))

    by_lot = realised + (market_value - cost_remaining)
    by_cashflow = market_value + proceeds - invested_gross
    assert by_lot == by_cashflow, f"P&L closure broken by {by_lot - by_cashflow}"


def test_gate_invariant_5_rebuild_is_deterministic(lines: list[str]) -> None:
    """`CLAUDE.md` invariant 10, from the statement rather than the CSV.

    A full rebuild — reparse, reimport, replay — must reproduce byte-identical
    derived output, which is what makes every derived table droppable.
    """
    a = build_book(import_cas(USER, lines, _resolve).txns).fingerprint()
    b = build_book(import_cas(USER, lines, _resolve).txns).fingerprint()
    assert a == b
